### PR TITLE
Feat/string formatting

### PR DESCRIPTION
**Pull request by GaspardCulis**
Properly implemented string format function

### CODE REVIEW

**Comment by GaspardCulis** [comment]
How are tests failing wtf

**Comment by pepp3rrr** [comment]
obv your checks fail because test-rw needs two files to tun with

**Review by pepp3rrr — CHANGES_REQUESTED** [review]
just change test-rw so it would take test_file1.txt and test_file2.txt instead of two files from the arguments

**Comment by pepp3rrr** [comment]
lets see what gaspard cooked this time

**Pull request merged**
