### PR TITLE
test/test_big

### PR DESCRIPTION
**Pull request by GaspardCulis**
Adding tests for checking if the current code plays well with big elem size params

### CODE REVIEW

**Comment by GaspardCulis** [comment]
Currently not working lemme fix that before merging

**Comment by GaspardCulis** [comment]
Currently not working lemme fix that before merging

**Review by pepp3rrr — CHANGES_REQUESTED** [review]
tests failing

**Comment by pepp3rrr** [comment]
bruh

**Comment by GaspardCulis** [comment]
NOOOOOOOOOOOO

**Pull request merged**
